### ISSUE TITLE
Bad Request when paying

### ISSUE THREAD

**Issue by 2ik** [hiqdev/omnipay-epayments#1]
**My code:**
```php
$gateway = Omnipay::create('ePayments');
$gateway->setPartnerId('id');
$gateway->setSecret('key');
$gateway->setTestMode(TRUE);

$response = $gateway->purchase([
      'orderId' => '1',
      'details' => 'details for payment',
      'amount' => '10.00',
      'currency' => 'USD',
      'returnUrl' => 'http://site.ru',
      'cancelUrl' => 'http://site.ru',
])->send();

if ($response->isRedirect()) {
      $response->redirect();
} elseif ($response->isSuccessful()) {
      print_r($response);
} else {
      echo $response->getMessage();
}
```

![Image](https://i.ibb.co/8P556tY/Screenshot-1.png)

ePayments changed api?

**Comment by SilverFire** [comment]
Just tested – works as it should in production mode. I don't have any ideas why right now

**Comment by 2ik** [comment]
Я первый раз имею дело с этим сервисом. В итоге прислали инструкцию, где алгоритм работает немного по другому и поля с другими названиями :confused:, пришлось написать свой простой класс. 
https://github.com/2ik/ePayments-PHP-Class
Редирект идет на https://api.sandbox.epayments.com/merchant все как и должно быть.

**Comment by SilverFire** [comment]
Странно, у нас почему-то всё работает. Может они выкатили только для новых юзеров такое

**Comment by SilverFire** [comment]
Закрываю задачу как не воспроизведённую
